// RUN: %dxr -generate-differentials %s | FileCheck %s

// When user::ad::fwd::Sphere already exists in the input, the rewriter
// must not emit a second forward-mode wrapper. The user's class is
// passed through verbatim and no auto-generated `struct Sphere : ::Sphere`
// block is appended for the fwd mode.

template <typename T> struct Value { T v; };

// CHECK: struct Sphere
// The user's existing wrapper is preserved.
// CHECK: namespace user
// CHECK: namespace ad
// CHECK: namespace fwd
// CHECK: struct Sphere : ::Sphere
// CHECK: Value<float>
// And the generator must not add a second wrapper with the autogenerated
// body.
// CHECK-NOT: ((this.radius * k) * k)
// CHECK-NOT: using namespace ::ad::fwd;

struct Sphere {
  float radius;
  [[dxc::autodiff(fwd)]]
  float area(float k) { return radius * k * k; }
};

namespace user { namespace ad { namespace fwd {
struct Sphere : ::Sphere {
  Value<float> area(Value<float> k) { return k; }
};
} } }

float main(float x : A) : SV_Target { Sphere s; return s.area(x); }
