#!/usr/bin/env python3
# Copyright (C) Microsoft Corporation. All rights reserved.
# This file is distributed under the University of Illinois Open Source License.
# See LICENSE.TXT for details.
"""Generate the HLSL embedded headers source file.

For every header file under ``tools/clang/lib/Headers/hlsl`` that the build
system has embedded with ``embed_header.py`` (one ``.inc`` per source file
under ``<build-dir>/<rel-path>.inc``), produce a single C++ source file
that:

1. Includes each ``.inc`` inside a uniquely-named namespace derived from
   the header's relative path (slashes and dots replaced with
   underscores), so that each file's ``Data`` StringRef variable gets its
   own namespace and never collides with another.

2. Defines ``clang::hlsl::getEmbeddedHeaders()``, returning a reference to
   a ``llvm::StringMap<llvm::StringRef>`` that maps each header's
   relative path under ``hlsl/`` (without a leading ``./`` or path
   separator) to the corresponding ``Data`` StringRef.
"""

import argparse
import os
import sys


def path_to_namespace(rel_path):
    """Convert a relative header path to a valid C++ namespace identifier.

    Slashes and dots are replaced with underscores so that
    ``dx/linalg.h`` becomes ``dx_linalg_h``.
    """
    out = []
    for ch in rel_path:
        if ch in ("/", "\\", "."):
            out.append("_")
        else:
            out.append(ch)
    return "".join(out)


def normalize_rel_path(rel_path):
    """Normalize a relative path to use forward slashes and no leading ./."""
    rel_path = rel_path.replace("\\", "/")
    while rel_path.startswith("./"):
        rel_path = rel_path[2:]
    return rel_path


def write_if_different(path, text):
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                if f.read() == text:
                    return
        except OSError:
            pass
    out_dir = os.path.dirname(path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def generate(output_path, entries):
    """Generate the source file.

    ``entries`` is an iterable of ``(rel_path, inc_path)`` pairs where
    ``rel_path`` is the path relative to ``hlsl/`` and ``inc_path`` is
    the absolute path to the ``.inc`` snippet produced by
    ``embed_header.py``.
    """
    entries = sorted(
        (normalize_rel_path(rel), inc) for rel, inc in entries)

    lines = []
    lines.append("// Generated by utils/generate_hlsl_embedded_headers.py.")
    lines.append("// Do not edit.")
    lines.append("")
    lines.append("#include \"clang/Lex/HLSLEmbeddedHeaders.h\"")
    lines.append("")
    lines.append("#include \"llvm/ADT/StringMap.h\"")
    lines.append("#include \"llvm/ADT/StringRef.h\"")
    lines.append("")
    lines.append("#include <utility>")
    lines.append("")

    for rel, inc in entries:
        ns = path_to_namespace(rel)
        # Use forward slashes in the include path so the generated file
        # is portable across host platforms.
        inc_fwd = inc.replace("\\", "/")
        lines.append("namespace {} {{".format(ns))
        lines.append("#include \"{}\"".format(inc_fwd))
        lines.append("}} // namespace {}".format(ns))
        lines.append("")

    lines.append("namespace clang {")
    lines.append("namespace hlsl {")
    lines.append("")
    lines.append(
        "const llvm::StringMap<llvm::StringRef> &getEmbeddedHeaders() {")
    lines.append("  static const llvm::StringMap<llvm::StringRef> Map = []() {")
    lines.append("    llvm::StringMap<llvm::StringRef> M;")
    for rel, _ in entries:
        ns = path_to_namespace(rel)
        lines.append("    M.insert(std::make_pair(llvm::StringRef(\"{}\"), {}::Data));".format(rel, ns))
    lines.append("    return M;")
    lines.append("  }();")
    lines.append("  return Map;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace hlsl")
    lines.append("} // namespace clang")
    lines.append("")

    write_if_different(output_path, "\n".join(lines))


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True,
                        help="Path to the generated C++ source file.")
    parser.add_argument(
        "--entry", action="append", default=[],
        metavar="REL_PATH=INC_PATH",
        help=("Relative header path (under hlsl/) and absolute path to its "
              "embedded .inc file. May be specified multiple times."))
    args = parser.parse_args(argv)

    entries = []
    for spec in args.entry:
        if "=" not in spec:
            parser.error("--entry must be of the form REL_PATH=INC_PATH")
        rel, inc = spec.split("=", 1)
        entries.append((rel, inc))

    generate(args.output, entries)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
